//
//  GitPullRequestsDetailViewModel.swift
//  Presentation
//
//  Created by Victor C Tavernari on 04/04/20.
//  Copyright (c) 2020 Taverna Apps. All rights reserved.
//
//  This file was generated by Mobiplus Clean
//

import Domain

class GitPullRequestsListViewModel: GitPullRequestsListViewModelInterface {
    var route = Observable<GitPullRequestsListViewModelRoute>(.none)
    var pullRequests = Observable<[GitPullRequestModel]>([])
    var isLoading = Observable<Bool>(false)
    var failMessage = Observable<String?>(nil)

    private let fetchPullRequestsUseCase: FetchPullRequestsUseCaseProtocol
    init(fetchPullRequestsUseCase: FetchPullRequestsUseCaseProtocol) {
        self.fetchPullRequestsUseCase = fetchPullRequestsUseCase
    }

    private var gitRepository: GitRepositoryModel!

    func load(repo: GitRepositoryModel) {
        gitRepository = repo
        fetchPullRequestsUseCase.execute(repo: repo)
    }

    func select(index: Int) {
        let pullRequest = pullRequests.value[index]
        route.value = .showPullRequestDetail(id: pullRequest.id, repo: gitRepository)
    }
}

extension GitPullRequestsListViewModel: FetchPullRequestsInterfaceAdapter {
    func doing() {
        isLoading.value = true
    }

    func done(data: [GitPullRequestModel]) {
        pullRequests.value = data
        isLoading.value = false
    }

    func failure(error: Error) {
        failMessage.value = error.localizedDescription
    }
}
