//
//  FetchGitRepositoriesError.swift
//  Domain
//
//  Created by Victor C Tavernari on 02/04/20.
//  Copyright (c) 2020 Taverna Apps. All rights reserved.
//
//  This file was generated by BLU Clean
//

import Foundation

public enum CommonError: LocalizedError {
    case noInternetConnection
    case timeOut
    case generic(String)
}

public enum FetchGitRepositoriesError: LocalizedError {
    case common(CommonError)
    case termCannotBeEmpty
}
