//
//  ListOfPullRequestsViewController.swift
//  Presentation
//
//  Created by Victor C Tavernari on 04/04/20.
//  Copyright (c) 2020 Taverna Apps. All rights reserved.
//
//  This file was generated by Mobiplus Clean 
//

import UIKit
import Domain

class ListOfPullRequestsViewController: UIViewController {

    final class func initWith(withViewModel viewModel: ListOfPullRequestsViewModel, andRepo repo: GitRepository) -> ListOfPullRequestsViewController {
        let vc = ListOfPullRequestsViewController()
        vc.viewModel = viewModel
        vc.repo = repo
        return vc
    }

    private(set) var viewModel: ListOfPullRequestsViewModel!
    private(set) var repo: GitRepository!

    private var dataSource: [GitPullRequest] = []

    @IBOutlet private weak var tableView: UITableView!

    fileprivate func configTableView() {
        tableView.register(R.nib.gitPullRequestsTableViewCell)
        tableView.rowHeight = UITableView.automaticDimension
        tableView.estimatedRowHeight = 90
        tableView.delegate = self
        tableView.dataSource = self
    }

    fileprivate func populateCell(index: Int, pullRequests: GitPullRequest, cell: GitPullRequestsTableViewCell) {
        cell.pullRequestAuthor = pullRequests.author
        cell.pullRequestImage = pullRequests.image
        cell.pullRequestTitle = pullRequests.title
        cell.pullRequestDescription = pullRequests.description
        cell.pullRequestDate = pullRequests.date?.string(format: .ddMMyyyyHHmmss) ?? ""
    }

    fileprivate func showError(message: String?) {

        guard let message = message else {
            return
        }

        let alert = UIAlertController(title: "Error", message: message, preferredStyle: UIAlertController.Style.alert)
        alert.addAction(UIAlertAction(title: "OK", style: UIAlertAction.Style.default, handler: nil))
        self.present(alert, animated: true, completion: nil)
    }

    fileprivate func deselectRow(indexPath: IndexPath) {
        self.tableView.cellForRow(at: indexPath)?.setSelected(false, animated: true)
    }

    fileprivate func handleLoadingView(_ value: Bool) {
        if value {
            self.showLoadingIndicator(text: "Loading")
        } else {
            self.removeLoadingIndicator()
        }
    }

    fileprivate func setDataSource(_ data: [GitPullRequest]) {
        self.dataSource = data
        self.tableView.reloadData()
    }

    fileprivate func bindViewModel() {
        self.viewModel.failMessage.observe(listener: self.showError)
        self.viewModel.isLoading.observe(listener: self.handleLoadingView)
        self.viewModel.pullRequests.observe(listener: self.setDataSource)
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "\(repo.name) Pull Requests"
        configTableView()
        viewModel.load(repo: repo)
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        bindViewModel()
    }

    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)

        self.viewModel.isLoading.removeAllObservers()
        self.viewModel.failMessage.removeAllObservers()
        self.viewModel.pullRequests.removeAllObservers()
    }
}

extension ListOfPullRequestsViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        self.viewModel.select(index: indexPath.row)
        self.deselectRow(indexPath: indexPath)
    }
}

extension ListOfPullRequestsViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return dataSource.count
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: R.reuseIdentifier.gitPullRequestsTableViewCell, for: indexPath)!
        let index = indexPath.row
        let data = self.dataSource[index]
        self.populateCell(index: index, pullRequests: data, cell: cell)
        return cell
    }

}
