//
//  PullRequestDetailsViewController.swift
//  Presentation
//
//  Created by Victor C Tavernari on 05/04/20.
//  Copyright (c) 2020 Taverna Apps. All rights reserved.
//
//  This file was generated by Mobiplus Clean 
//

import UIKit
import Domain
import Alamofire
import AlamofireImage

class PullRequestDetailsViewController: UIViewController {

    @IBOutlet private weak var containerView: UIView!
    @IBOutlet private weak var authorLabel: UILabel!
    @IBOutlet private weak var titleLabel: UILabel!
    @IBOutlet private weak var descriptionLabel: UILabel!
    @IBOutlet private weak var dateLabel: UILabel!
    @IBOutlet private weak var imageView: UIImageView!
    @IBOutlet private weak var commentsLabel: UILabel!
    @IBOutlet private weak var commitsLabel: UILabel!
    @IBOutlet private weak var additionsLabel: UILabel!
    @IBOutlet private weak var deletionsLabel: UILabel!
    @IBOutlet private weak var changedFilesLabel: UILabel!

    final class func initWith(viewModel: PullRequestDetailsViewModelInterface, id: Int, repo: GitRepository) -> PullRequestDetailsViewController {
        let vc = PullRequestDetailsViewController()
        vc.viewModel = viewModel
        vc.id = id
        vc.repo = repo
        return vc
    }

    private(set) var viewModel: PullRequestDetailsViewModelInterface!
    private(set) var id: Int!
    private(set) var repo: GitRepository!

    fileprivate func populateView(data: GitPullRequest?) {

        guard let data = data else {
            return
        }

        self.titleLabel.text = data.title
        self.authorLabel.text = data.author
        self.descriptionLabel.text = data.description
        self.commitsLabel.text = "Commits: \(data.commitsCount)"
        self.commentsLabel.text = "Comments: \(data.commentsCount)"
        self.additionsLabel.text = "Additions: \(data.additionsCount)"
        self.deletionsLabel.text = "Deletions: \(data.deletionsCount)"
        self.changedFilesLabel.text = "Changed Files: \(data.changedFilesCount)"
        self.dateLabel.text = data.date!.string(format: .ddMMyyyyHHmmss)

        if let url = try? data.image.asURL() {
            self.imageView.loadCircleImage(url: url)
        }
    }

    fileprivate func showError(message: String?) {
        guard let message = message else {
            return
        }

        let alert = UIAlertController(title: "Error", message: message, preferredStyle: UIAlertController.Style.alert)
        alert.addAction(UIAlertAction(title: "OK", style: UIAlertAction.Style.default, handler: nil))
        self.present(alert, animated: true, completion: nil)
    }

    fileprivate func handleIsLoading(_ isLoading: Bool) {
        if isLoading {
            self.showLoadingIndicator(text: "Loading")
        } else {
            self.removeLoadingIndicator()
        }
    }

    fileprivate func bindToViewModel() {
        self.viewModel.isLoading.observe(listener: self.handleIsLoading)
        self.viewModel.failMessage.observe(listener: self.showError)
        self.viewModel.pullRequest.observe(listener: self.populateView)
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        title = "Pull Request Detail"
        viewModel.load(pullRequestid: id, fromRepo: repo)
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        bindToViewModel()
    }
}
