//
//  PullRequestDetailsViewModelRoute.swift
//  Presentation
//
//  Created by Victor C Tavernari on 05/04/20.
//  Copyright (c) 2020 Taverna Apps. All rights reserved.
//
//  This file was generated by Mobiplus Clean 
//

import Foundation

enum PullRequestDetailsViewModelRoute: Equatable {
    case none
}
