//
//  FetchPullRequestDetailUseCase.swift
//  Domain
//
//  Created by Victor C Tavernari on 04/04/20.
//  Copyright (c) 2020 Taverna Apps. All rights reserved.
//
//  This file was generated by Mobiplus Clean
//

import Foundation

public class FetchPullRequestDetailUseCase: FetchPullRequestDetailUseCaseInterface {
    public var delegateInterfaceAdapter: FetchPullRequestDetailInterfaceAdapter?

    private let repository: GitPullRequestRepositoryInterface

    public init(repository: GitPullRequestRepositoryInterface) {
        self.repository = repository
    }

    public func execute(id: Int, fromRepo repo: GitRepository) {
        delegateInterfaceAdapter?.doing()
        repository.get(id: id, fromRepo: repo) { result in
            do {
                let pullRequest = try result.handle()
                self.delegateInterfaceAdapter?.done(data: pullRequest)
            } catch { self.delegateInterfaceAdapter?.failure(error: error) }
        }
    }
}
