# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :test do
    scan(
      skip_build: true,
      workspace: ENV['XCODE_WORKSPACE'],
      scheme: ENV['XCODE_PRESENTATION_SCHEME'],
      clean: true,
      code_coverage: true,
    )

    slather(
      circleci: true,
      cobertura_xml: true,
      output_directory: './',
      workspace: ENV['XCODE_WORKSPACE'],
      scheme: ENV['XCODE_PRESENTATION_SCHEME'],
      proj: "#{ENV['XCODE_PRESENTATION_SCHEME']}/#{ENV['XCODE_PRESENTATION_SCHEME']}.xcodeproj",
      ignore: [
        '../../../Library/*',
        '**/DerivedData/*',
        'Pods/*'
      ]
    )
  end
end
