//
//  ListOfRepositoriesViewModelRoute.swift
//  Presentation
//
//  Created by Victor C Tavernari on 04/04/20.
//  Copyright (c) 2020 Taverna Apps. All rights reserved.
//
//  This file was generated by Mobiplus Clean 
//

import Domain

enum ListOfRepositoriesViewModelRoute: Equatable {
    case none
    case showPullRequests(repo: GitRepository)
    case showError(errorMessage: String)
}
