//
//  GitPullRequestsListViewModelInterface.swift
//  Presentation
//
//  Created by Victor C Tavernari on 04/04/20.
//  Copyright (c) 2020 Taverna Apps. All rights reserved.
//
//  This file was generated by Mobiplus Clean
//

import DomainLayer

protocol GitPullRequestsListViewModelInterface {
    var pullRequests: Observable<[GitPullRequestModel]> { get }
    var route: Observable<GitPullRequestsListViewModelRoute> { get }
    var isLoading: Observable<Bool> { get }
    var failMessage: Observable<String?> { get }

    func select(index: Int)
    func load(repo: GitRepositoryModel)
}
