//
//  GitPullRequestDetailsViewModelInterface.swift
//  Presentation
//
//  Created by Victor C Tavernari on 05/04/20.
//  Copyright (c) 2020 Taverna Apps. All rights reserved.
//
//  This file was generated by Mobiplus Clean
//

import Domain

protocol GitPullRequestDetailsViewModelInterface {
    var route: Observable<GitPullRequestDetailsViewModelRoute> { get }
    var isLoading: Observable<Bool> { get }
    var failMessage: Observable<String?> { get }
    var pullRequest: Observable<GitPullRequestModel?> { get }

    func load(pullRequestid: Int, fromRepo repo: GitRepositoryModel)
}
